# Prometheus configuration for Arbitrage Detection Service
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'arbitrage-service'
    
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    
    static_configs:
      - targets: ['localhost:8000']
        labels:
          service: 'arbitrage-detection'
          environment: 'production'
          instance: 'arbitrage-app-1'

  # Optional: Add other services you want to monitor
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
