[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "arbitrage_app"
version = "0.1.0"
description = "A package for arbitrage calculations"
requires-python = ">=3.6"